variables:
  GIT_VERSION: v2.30.1
  COMMIT_MESSAGE: "build project ${CI_COMMIT_SHORT_SHA} on branch ${CI_COMMIT_REF_SLUG} at ${CI_COMMIT_TIMESTAMP}"

debug:
  image: alpine:latest
  script: 
    - echo ${COMMIT_MESSAGE}