variables:
  GIT_VERSION: v2.30.1
  COMMIT_MESSAGE: "build project ${CI_COMMIT_SHORT_SHA} on branch ${CI_COMMIT_REF_SLUG} at ${CI_COMMIT_TIMESTAMP}"

build-html:
  image: alpine:latest
  before_script:
    - mkdir -p build
  script: 
    - cp index.html build/
  artifacts:
    name: "$CI_JOB_NAME-${CI_COMMIT_SHORT_SHA}"
    paths:
      - build/*