variables:
  DIR_BUILD: build

build-html:
  image: alpine:latest
  before_script:
    - mkdir -p ${DIR_BUILD}
    - touch ${DIR_BUILD}/.nojekyll
  script: 
    - cp index.html ${DIR_BUILD}/
  artifacts:
    name: "$CI_JOB_NAME-${CI_COMMIT_SHORT_SHA}"
    paths:
      - ${DIR_BUILD}/*

deploy-pages:
  image: 
    entrypoint: ['']
    name: alpine/git:${GIT_VERSION}
  variables:
    GIT_VERSION: v2.30.1  
    PUSH_OPTIONS: --force
    COMMIT_MESSAGE: "build project ${CI_COMMIT_SHORT_SHA} on branch ${CI_COMMIT_REF_SLUG} at ${CI_COMMIT_TIMESTAMP}"
    GIT_LOCAL_BRANCH: main
    GIT_REMOTE_BRANCH: github-pages
    GIT_REMOTE_REPO: "https://${GIT_ACTOR}:${GIT_ACCESS_TOKEN}@gitlab.dimas-maryanto.com/examples/gitlab-ci-cd/gitlab-ci-push-new-branch.git"
  needs:
    - build-html
  before_script:
    - cd ${DIR_BUILD}
    - git init -b $GIT_LOCAL_BRANCH
    - git config --global user.email "${GIT_ACTOR}@users.noreply.gitlab.com"
    - git config --global user.name "${GIT_ACTOR}"
  script: 
    - git add .
    - git commit $COMMIT_OPTIONS -m ${COMMIT_MESSAGE}
    - git push $PUSH_OPTIONS $GIT_REMOTE_REPO $GIT_LOCAL_BRANCH:$GIT_REMOTE_BRANCH
